const data = {
    'Death Knight': {
        'BLOOD': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Winding Sheet',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'T10 Hands',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Might of Blight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': ['Shadowmourne', 'Glorenzelg, High-Blade of the Silver Hand'],
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Sigil of the Hanged Man',
        },
        'FROST ARP': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Garrosh\'s Rage',
            'Chest': 'T10 Chest',
            'Wrist': 'Toskk\'s Maximized Wristguards',
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Might of Blight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Relic/Ranged': 'Sigil of Awareness',
        },
        'FROST STR': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Winding Sheet',
            'Chest': 'T10 Chest',
            'Wrist': 'Polar Bear Claw Bracers',
            'Hands': 'Fleshrending Gauntlets',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Might of Blight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Relic/Ranged': 'Sigil of the Hanged Man',
        },
        'UNHOLY': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Winding Sheet',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'T10 Hands',
            'Waist': 'Coldwraith Links',
            'Legs': 'Scourge Reaver\'s Legplates',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Might of Blight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': ['Shadowmourne', 'Glorenzelg, High-Blade of the Silver Hand'],
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Sigil of the Hanged Man',
        },
        'UNHOLY (Expertise)': {
            'Head': 'T10 Head',
            'Neck': 'Lana\'thel\'s Chain of Flagellation',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Winding Sheet',
            'Chest': 'T10 Chest',
            'Wrist': 'Polar Bear Claw Bracers',
            'Hands': 'Fleshrending Gauntlets',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Skeleton Lord\'s Circle',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': ['Shadowmourne', 'Glorenzelg, High-Blade of the Silver Hand'],
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Sigil of the Hanged Man',
        },
        'TANK': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Treads of Impending Resurrection',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Juggernaut\'s Vitality',
            'Weapon': ['Cryptmaker', 'Bryntroll, the Bone Arbiter'],
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Sigil of Insolence',
        },
        'EXPERTISE SET': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Royal Crimson Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Grinning Skull Greatboots',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Juggernaut\'s Vitality',
            'Weapon': 'Glorenzelg, High-Blade of the Silver Hand',
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Sigil of Insolence',
        },
    },
    'Druid': {
        'STR CAT': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'T10 Chest',
            'Wrist': 'Toskk\'s Maximized Wristguards',
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': 'Frostbitten Fur Boots',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Oathbinder, Charge of the Ranger-General',
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Idol of the Crying Moon',
        },
        'HASTE CAT': {
            'Head': 'T10 Head',
            'Neck': 'Sindragosa\'s Cruel Claw',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Shadowvault Slayer\'s Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': 'Frostbitten Fur Boots',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Oathbinder, Charge of the Ranger-General',
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Idol of the Crying Moon',
        },
        'BEAR': {
            'Head': 'T10 Head',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'Ikfirus\'s Sack of Wonder',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'T10 Hands',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': ['Frostbitten Fur Boots', 'Footpads of Impending Death (Expertise)'],
            'Ring 1': ['Signified ring of Binding', 'Signet of Twilight'],
            'Ring 2': 'Devium\'s Eternally Cold Ring',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Juggernaut\'s Vitality',
            'Weapon': ['Cryptmaker', 'Oathbinder, Charge of the Ranger-General', 'Wrathful Gladiator\'s Halberd'],
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Idol of the Crying Moon',
        },
        'BALANCE': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': ['Ring of Rapid Ascent', 'Valanar\'s other Signet Ring'],
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Idol of the Lunar Eclipse',
        },
        'RESTORATION': {
            'Head': 'T10 Head',
            'Neck': 'Bone Sentinel\'s Amulet',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Greatcloak of the Turned Champion',
            'Chest': 'Sanguine Silk Robes',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Professor\'s Bloodied Smock',
            'Legs': 'T10 Legs',
            'Feet': ['Boots of Unnatural Growth', 'Plague Scientist\'s Boots (If Val\'anyr)'],
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Memory of Malygos',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': 'Althor\'s Abacus',
            'Weapon': ['Val\'anyr, Hammer of Ancient Kings', 'Royal Scepter of Terenas II, Trauma'],
            'Offhand/Shield': 'Sundial of Eternal Dusk',
            'Relic/Ranged': 'Idol of the Black Willow',
        },
    },
    'Hunter': {
        'MARKSMANSHIP': {
            'Head': 'T10 Head',
            'Neck': ['Rimetooth Pendant', 'Sindragosa\'s Cruel Claw'],
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'T10 Chest',
            'Wrist': 'Scourge Hunter\'s Vambraces',
            'Hands': 'T10 Hands',
            'Waist': 'Nerub\'ar Stalker\'s Cord',
            'Legs': 'Leggings of Northern Lights',
            'Feet': 'Returning Footfalls',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Frostbrood Sapphire Ring',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Oathbinder, Charge of the Ranger-General',
            'Offhand/Shield': '-',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
    },
    'Mage': {
        'TORMENT OF THE WEAK': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'Robe of the Walking Nightmare',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'ARCANE': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Dislodged Foreign Object',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
    },
    'Paladin': {
        'HOLY': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'Rot-Resistant Breastplate',
            'Wrist': ['Bracers of Fiery Night', 'Phaseshifter\'s Bracers'],
            'Hands': 'Fallen Lord\'s Handguards',
            'Waist': 'Split Shape Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Foreshadow Steps',
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': ['Meteorite Crystal', 'Talisman of Resurgence'],
            'Weapon': ['Royal Scepter of Terenas II', 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony'],
            'Offhand/Shield': 'Bulwark of Smouldering Steel',
            'Relic/Ranged': 'Libram of Renewal',
        },
        'RET AGILITY': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Shadowvault Slayer\'s Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'Anub\'ar Stalker\'s Gloves',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Sharpened Twilight Scale',
            'Trinket 2': 'Tiny Abomination in a Jar',
            'Weapon': ['Shadowmourne', 'Oathbinder, Charge of the Ranger-General'],
            'Offhand/Shield': '-',
            'Relic/Ranged': ['Libram of Valiance', 'Libram of Three Truths'],
        },
        'RET STRENGTH (AOE)': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Winding Sheet',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'Fleshrending Gauntlets',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Might',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Death\'s Choice',
            'Trinket 2': 'Tiny Abomination in a Jar',
            'Weapon': ['Shadowmourne', 'Glorenzelg, High-Blade of the Silver Hand'],
            'Offhand/Shield': '-',
            'Relic/Ranged': ['Libram of Valiance', 'Libram of Three Truths'],
        },
        'PROT': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Treads of Impending Resurrection',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': ['Petrified Twilight Scale', 'Juggernaut\'s Vitality'],
            'Weapon': ['Bloodvenom Blade', 'Mithrios, Bronzebeard\'s Legacy'],
            'Offhand/Shield': 'Icecrown Glacial Wall',
            'Relic/Ranged': ['Libram of Sacred Shield', 'Libram of Valiance', 'Libram of Eternal Tower'],
        },
        'PROT (ARMOR)': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'Spaulders of the Blood Princes',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': 'Pillars of Might',
            'Feet': 'Treads of Impending Resurrection',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Petrified Twilight Scale',
            'Weapon': 'Mithrios, Bronzebeard\'s Legacy',
            'Offhand/Shield': 'Icecrown Glacial Wall',
            'Relic/Ranged': 'Libram of Sacred Shield',
        },
        'EXPERTISE SET': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Grinning Skull Greatboots',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Petrified Twilight Scale',
            'Weapon': 'Mithrios, Bronzebeard\'s Legacy',
            'Offhand/Shield': 'Icecrown Glacial Wall',
            'Relic/Ranged': ['Libram of Sacred Shield', 'Libram of Eternal Tower'],
        },
    },
    'Priest': {
        'SHADOW (BiS)': {
            'Head': 'T10 Head',
            'Neck': 'Amulet of Silent Eulogy',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'Gunship Captain\'s Mittens',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'SHADOW (2nd BiS)': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Loop of the Endless Labyrinth',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'DISCIPLINE': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest (Shadow Set)',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Lingering Illness',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': ['Althor\'s Abacus', 'Solace of the Fallen'],
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'DISCIPLINE - 2': {
            'Head': 'T10 Head',
            'Neck': 'Holiday\'s Grace',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Lingering Illness',
            'Legs': 'T10 Legs (Shadow)',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Ring of Maddening Whispers',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': 'Althor\'s Abacus',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Nightmare Ender',
        },
        'HOLY': {
            'Head': 'T10 Head',
            'Neck': 'Bone Sentinel\'s Amulet',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Greatcloak of the Turned Champion',
            'Chest': 'Sanguine Silk Robes',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Memory of Malygos',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': 'Althor\'s Abacus',
            'Weapon': ['Val\'anyr, Hammer of Ancient Kings', 'Royal Scepter of Terenas II'],
            'Offhand/Shield': 'Sundial of Eternal Dusk',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
    },
    'Rogue': {
        'COMBAT 2P': {
            'Head': 'T10 Head',
            'Neck': 'Sindragosa\'s Cruel Claw',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'Ikfirus\'s Sack of Wonder',
            'Wrist': ['Umbrage Armbands', 'Toskk\'s Maximized Wristguards'],
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'Gangrenous Leggings',
            'Feet': 'Frostbitten Fur Boots',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Frostbrood Sapphire Ring',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Scourgeborne Waraxe',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
        'COMBAT 4P': {
            'Head': 'T10 Head',
            'Neck': 'Sindragosa\'s Cruel Claw',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'T10 Chest',
            'Wrist': ['Umbrage Armbands', 'Toskk\'s Maximized Wristguards'],
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': 'Frostbitten Fur Boots',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Scourgeborne Waraxe',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
        'ASSASSINATION': {
            'Head': 'T10 Head',
            'Neck': 'Sindragosa\'s Cruel Claw',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Shadowvault Slayer\'s Cloak',
            'Chest': 'Ikfirus\'s Sack of Wonder',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'T10 Hands',
            'Waist': 'Astrylian\'s Sutured Cinch',
            'Legs': 'T10 Legs',
            'Feet': 'Frostbitten Fur Boots',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Tiny Abomination in a Jar',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Heaven\'s Fall, Kryss of a Thousand Lies',
            'Offhand/Shield': 'Lungbreaker',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
    },
    'Shaman': {
        'ELEMENTAL CRIT MULTI-TARGET': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'Horrific Flesh Epaulets',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Split Shape Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Loop of the Endless Labyrinth',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Bulwark of Smouldering Steel',
            'Relic/Ranged': ['Bizuri\'s Totem of Shattered Ice', 'Totem of Hex'],
        },
        'ELEMENTAL HASTE': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Split Shape Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Valanar\'s other Signet Ring',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Bulwark of Smouldering Steel',
            'Relic/Ranged': 'Bizuri\'s Totem of Shattered Ice',
        },
        'RESTORATION': {
            'Head': 'T10 Head',
            'Neck': 'Blood Queen\'s Crimson Choker',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': ['Bracers of Fiery Night', 'Phaseshifter\'s Bracers'],
            'Hands': ['Changeling Gloves', 'Unclean Surgical Gloves'],
            'Waist': 'Split Shape Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ring of Phased Regeneration',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Glowing Twilight Scale',
            'Trinket 2': 'Solace of the Fallen',
            'Weapon': 'Royal Scepter of Terenas II',
            'Offhand/Shield': 'Bulwark of Smouldering Steel',
            'Relic/Ranged': ['Totem of Calming Tides', 'Bizuri\'s Totem of Shattered Ice'],
        },
        'ENHANCEMENT SINGLE TARGET': {
            'Head': 'T10 Head',
            'Neck': 'Sindragosa\'s Cruel Claw',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Shadowvault Slayer\'s Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Scourge Hunter\'s Vambraces',
            'Hands': 'Anub\'ar Stalker\'s Gloves',
            'Waist': 'Nerub\'ar Stalker\'s Cord',
            'Legs': 'T10 Legs',
            'Feet': 'Returning Footfalls',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Relic/Ranged': 'Totem of the Avalanche',
        },
        'ENHANCEMENT MULTI-TARGET': {
            'Head': 'T10 Head',
            'Neck': 'Precious\'s Putrid Collar',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Shadowvault Slayer\'s Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Umbrage Armbands',
            'Hands': 'Anub\'ar Stalker\'s Gloves',
            'Waist': 'Nerub\'ar Stalker\'s Cord',
            'Legs': 'T10 Legs',
            'Feet': 'Returning Footfalls',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Signet of Twilight',
            'Trinket 1': 'Herkuml War Token',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Offhand/Shield': 'Havoc\'s Call, Blade of Lordaeron Kings',
            'Relic/Ranged': 'Bizuri\'s Totem of Shattered Ice',
        },
    },
    'Warlock': {
        'DEMONOLOGY': {
            'Head': 'T10 Head',
            'Neck': 'Amulet of Silent Eulogy',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Valanar\'s other Signet Ring',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'DESTRUCTION': {
            'Head': 'T10 Head',
            'Neck': 'Amulet of Silent Eulogy',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'Gunship Captain\'s Mittens',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'T10 Legs',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Valanar\'s other Signet Ring',
            'Trinket 1': 'Phylactery of the Nameless Lich',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
        'AFFLICTION': {
            'Head': 'T10 Head',
            'Neck': 'Amulet of Silent Eulogy',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Cloak of Burning Dusk',
            'Chest': 'T10 Chest',
            'Wrist': 'Bracers of Fiery Night',
            'Hands': 'T10 Hands',
            'Waist': 'Crushing Coldwraith Belt',
            'Legs': 'Plaguebringer\'s Stained Pants',
            'Feet': 'Plague Scientist\'s Boots',
            'Ring 1': 'Ashen Band of Endless Destruction',
            'Ring 2': 'Ring of Rapid Ascent',
            'Trinket 1': 'Dislodged Foreign Object',
            'Trinket 2': 'Charred Twilight Scale',
            'Weapon': 'Bloodsurge, Kel\'Thuzad\'s Blade of Agony',
            'Offhand/Shield': 'Shadow Silk Spindle',
            'Relic/Ranged': 'Corpse Impaling Spike',
        },
    },
    'Warrior': {
        'FURY': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'T10 Chest',
            'Wrist': ['Umbrage Armbands', 'Toskk\'s Maximized Wristguards'],
            'Hands': 'Aldriana\'s Gloves of Secrecy',
            'Waist': 'Coldwraith Links',
            'Legs': 'T10 Legs',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Frostbrood Sapphire Ring',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Shadowmourne',
            'Offhand/Shield': 'Glorenzelg, High-Blade of the Silver Hand',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
        'Fury (No SM)': {
            'Head': 'T10 Head',
            'Neck': 'Penumbra Pendant',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sylvana\'s Cunning',
            'Chest': 'T10 Chest',
            'Wrist': ['Umbrage Armbands', 'Toskk\'s Maximized Wristguards'],
            'Hands': 'T10 Hands',
            'Waist': 'Coldwraith Links',
            'Legs': 'Leggings of Northern Lights',
            'Feet': 'Apocolypse Advance',
            'Ring 1': 'Ashen Band of Endless Vengeance',
            'Ring 2': 'Frostbrood Sapphire Ring',
            'Trinket 1': 'Deathbringer\'s Will',
            'Trinket 2': 'Sharpened Twilight Scale',
            'Weapon': 'Glorenzelg, High-Blade of the Silver Hand',
            'Offhand/Shield': 'Glorenzelg, High-Blade of the Silver Hand',
            'Relic/Ranged': 'Fal\'inrush, Defender of Quel\'thalas',
        },
        'PROTECTION': {
            'Head': 'Broken Ram Skull Helm',
            'Neck': 'Bile-Encrusted Medallion',
            'Shoulders': 'T10 Shoulders',
            'Back': 'Sentinel\'s Winter Cloak',
            'Chest': 'T10 Chest',
            'Wrist': 'Gargoyle Spit Bracers',
            'Hands': 'T10 Hands',
            'Waist': 'Verdigris Chain Belt',
            'Legs': ['T10 Legs', 'Pillars of Might'],
            'Feet': 'Treads of Impending Resurrection',
            'Ring 1': 'Devium\'s Eternally Cold Ring',
            'Ring 2': 'Signified ring of Binding',
            'Trinket 1': 'Sindragosa\'s Flawless Fang',
            'Trinket 2': 'Petrified Twilight Scale',
            'Weapon': ['Bloodvenom Blade', 'Mithrios, Bronzebeard\'s Legacy'],
            'Offhand/Shield': 'Icecrown Glacial Wall',
            'Relic/Ranged': 'Dreamhunter\'s Carbine',
        },
    },
}
