const data = {
    'Death Knight': {
        'BLOOD': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51312/" target="_blank">T10 Head (Sanctified Scourgelord Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51314/" target="_blank">T10 Shoulders (Sanctified Scourgelord Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50677/" target="_blank">Winding Sheet</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51310/" target="_blank">T10 Chest (Sanctified Scourgelord Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51311/" target="_blank">T10 Hands (Sanctified Scourgelord Gauntlets)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51313/" target="_blank">T10 Legs (Sanctified Scourgelord Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50693/" target="_blank">Might of Blight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>', '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50459/" target="_blank">Sigil of the Hanged Man</a>',
        },
        'FROST ARP': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51312/" target="_blank">T10 Head (Sanctified Scourgelord Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51314/" target="_blank">T10 Shoulders (Sanctified Scourgelord Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47548/" target="_blank">Garrosh\'s Rage</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51310/" target="_blank">T10 Chest (Sanctified Scourgelord Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51313/" target="_blank">T10 Legs (Sanctified Scourgelord Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50693/" target="_blank">Might of Blight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=40207/" target="_blank">Sigil of Awareness</a>',
        },
        'FROST STR': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51312/" target="_blank">T10 Head (Sanctified Scourgelord Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51314/" target="_blank">T10 Shoulders (Sanctified Scourgelord Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50677/" target="_blank">Winding Sheet</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51310/" target="_blank">T10 Chest (Sanctified Scourgelord Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50659/" target="_blank">Polar Bear Claw Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50690/" target="_blank">Fleshrending Gauntlets</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51313/" target="_blank">T10 Legs (Sanctified Scourgelord Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50693/" target="_blank">Might of Blight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50459/" target="_blank">Sigil of the Hanged Man</a>',
        },
        'UNHOLY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51312/" target="_blank">T10 Head (Sanctified Scourgelord Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51314/" target="_blank">T10 Shoulders (Sanctified Scourgelord Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50677/" target="_blank">Winding Sheet</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51310/" target="_blank">T10 Chest (Sanctified Scourgelord Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51311/" target="_blank">T10 Hands (Sanctified Scourgelord Gauntlets)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50624/" target="_blank">Scourge Reaver\'s Legplates</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50693/" target="_blank">Might of Blight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>', '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50459/" target="_blank">Sigil of the Hanged Man</a>',
        },
        'UNHOLY (Expertise)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51312/" target="_blank">T10 Head (Sanctified Scourgelord Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50728/" target="_blank">Lana\'thel\'s Chain of Flagellation</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51314/" target="_blank">T10 Shoulders (Sanctified Scourgelord Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50677/" target="_blank">Winding Sheet</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51310/" target="_blank">T10 Chest (Sanctified Scourgelord Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50659/" target="_blank">Polar Bear Claw Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50690/" target="_blank">Fleshrending Gauntlets</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51313/" target="_blank">T10 Legs (Sanctified Scourgelord Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50657/" target="_blank">Skeleton Lord\'s Circle</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>', '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50459/" target="_blank">Sigil of the Hanged Man</a>',
        },
        'TANK': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51309/" target="_blank">T10 Shoulders (Sanctified Scourgelord Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51305/" target="_blank">T10 Chest (Sanctified Scourgelord Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51307/" target="_blank">T10 Hands (Sanctified Scourgelord Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51308/" target="_blank">T10 Legs (Sanctified Scourgelord Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54579/" target="_blank">Treads of Impending Resurrection</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=47451/" target="_blank">Juggernaut\'s Vitality</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=50603/" target="_blank">Cryptmaker</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50709/" target="_blank">Bryntroll, the Bone Arbiter</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=47672/" target="_blank">Sigil of Insolence</a>',
        },
        'EXPERTISE SET': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51309/" target="_blank">T10 Shoulders (Sanctified Scourgelord Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50718/" target="_blank">Royal Crimson Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51305/" target="_blank">T10 Chest (Sanctified Scourgelord Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51307/" target="_blank">T10 Hands (Sanctified Scourgelord Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51308/" target="_blank">T10 Legs (Sanctified Scourgelord Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50625/" target="_blank">Grinning Skull Greatboots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=47451/" target="_blank">Juggernaut\'s Vitality</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>',
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=47672/" target="_blank">Sigil of Insolence</a>',
        },
    },
    'Druid': {
        'STR CAT': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51296/" target="_blank">T10 Head (Sanctified Lasherweave Headguard)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51299/" target="_blank">T10 Shoulders (Sanctified Lasherweave Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51298/" target="_blank">T10 Chest (Sanctified Lasherweave Raiment)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51297/" target="_blank">T10 Legs (Sanctified Lasherweave Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50735/" target="_blank">Oathbinder, Charge of the Ranger-General</a>',
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50456/" target="_blank">Idol of the Crying Moon</a>',
        },
        'HASTE CAT': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51296/" target="_blank">T10 Head (Sanctified Lasherweave Headguard)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51299/" target="_blank">T10 Shoulders (Sanctified Lasherweave Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50653/" target="_blank">Shadowvault Slayer\'s Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51298/" target="_blank">T10 Chest (Sanctified Lasherweave Raiment)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51297/" target="_blank">T10 Legs (Sanctified Lasherweave Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50735/" target="_blank">Oathbinder, Charge of the Ranger-General</a>',
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50456/" target="_blank">Idol of the Crying Moon</a>',
        },
        'BEAR': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51296/" target="_blank">T10 Head (Sanctified Lasherweave Headguard)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51299/" target="_blank">T10 Shoulders (Sanctified Lasherweave Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50656/" target="_blank">Ikfirus\'s Sack of Wonder</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51295/" target="_blank">T10 Hands (Sanctified Lasherweave Handgrips)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51297/" target="_blank">T10 Legs (Sanctified Lasherweave Legguards)</a>',
            'Feet': ['<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=49895/" target="_blank">Footpads of Impending Death (Expertise)</a>'],
            'Ring 1': ['<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>'],
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=47451/" target="_blank">Juggernaut\'s Vitality</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=50603/" target="_blank">Cryptmaker</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50735/" target="_blank">Oathbinder, Charge of the Ranger-General</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=51481/" target="_blank">Wrathful Gladiator\'s Halberd</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50456/" target="_blank">Idol of the Crying Moon</a>',
        },
        'BALANCE': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=Signet of Twilight/" target="_blank">T10 Head (Sanctified Lasherweave Cover)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51292/" target="_blank">T10 Shoulders (anctified Lasherweave Mantle)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51294/" target="_blank">T10 Chest (Sanctified Lasherweave Vestment)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51291/" target="_blank">T10 Hands (Sanctified Lasherweave Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51293/" target="_blank">T10 Legs (Sanctified Lasherweave Trousers)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': ['<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>', 
            '<a href="https://www.wowhead.com/wotlk/item=50714/" target="_blank">Valanar\'s other Signet Ring</a>'],
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50457/" target="_blank">Idol of the Lunar Eclipse</a>',
        },
        'RESTORATION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51302/" target="_blank">T10 Head (anctified Lasherweave Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50609/" target="_blank">Bone Sentinel\'s Amulet</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51304/" target="_blank">T10 Shoulders (Sanctified Lasherweave Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50668/" target="_blank">Greatcloak of the Turned Champion</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50717/" target="_blank">Sanguine Silk Robes</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51301/" target="_blank">T10 Hands (anctified Lasherweave Gauntlets)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50705/" target="_blank">Professor\'s Bloodied Smock</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51303/" target="_blank">T10 Legs (Sanctified Lasherweave Legplates)</a>',
            'Feet': ['<a href="https://www.wowhead.com/wotlk/item=50665/" target="_blank">Boots of Unnatural Growth</a>', 
            '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots (If Val\'anyr)</a>'],
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50636/" target="_blank">Memory of Malygos</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=50366/" target="_blank">Althor\'s Abacus</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=46017/" target="_blank">Val\'anyr, Hammer of Ancient Kings</a>', 
            '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>'],
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50635/" target="_blank">Sundial of Eternal Dusk</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50454/" target="_blank">Idol of the Black Willow</a>',
        },
    },
    'Hunter': {
        'MARKSMANSHIP': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51286/" target="_blank">T10 Head (Sanctified Ahn\'Kahar Blood Hunter\'s Headpiece)</a>',
            'Neck': ['<a href="https://www.wowhead.com/wotlk/item=51822/" target="_blank">Rimetooth Pendant</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>'],
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51288/" target="_blank">T10 Shoulders (Sanctified Ahn\'Kahar Blood Hunter\'s Spaulders)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51289/" target="_blank">T10 Chest (Sanctified Ahn\'Kahar Blood Hunter\'s Tunic)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50655/" target="_blank">Scourge Hunter\'s Vambraces</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51285/" target="_blank">T10 Hands (Sanctified Ahn\'Kahar Blood Hunter\'s Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50688/" target="_blank">Nerub\'ar Stalker\'s Cord</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50645/" target="_blank">Leggings of Northern Lights</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54577/" target="_blank">Returning Footfalls</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50618/" target="_blank">Frostbrood Sapphire Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50735/" target="_blank">Oathbinder, Charge of the Ranger-General</a>',
            'Offhand/Shield': '-',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
    },
    'Mage': {
        'TORMENT OF THE WEAK': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51281/" target="_blank">T10 Head (Sanctified Bloodmage Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51284/" target="_blank">T10 Shoulders (Sanctified Bloodmage Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50629/" target="_blank">Robe of the Waking Nightmare</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51280/" target="_blank">T10 Hands (Sanctified Bloodmage Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51282/" target="_blank">T10 Legs (Sanctified Bloodmage Leggings)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'ARCANE': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51281/" target="_blank">T10 Head (Sanctified Bloodmage Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51284/" target="_blank">T10 Shoulders (Sanctified Bloodmage Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51283/" target="_blank">T10 Chest (Sanctified Bloodmage Robe)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51280/" target="_blank">T10 Hands (Sanctified Bloodmage Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50348/" target="_blank">Dislodged Foreign Object</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
    },
    'Paladin': {
        'HOLY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51272/" target="_blank">T10 Head (Sanctified Lightsworn Headpiece)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51273/" target="_blank">T10 Shoulders (Sanctified Lightsworn Spaulders)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50680/" target="_blank">Rot-Resistant Breastplate</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=54584/" target="_blank">Phaseshifter\'s Bracers</a>'],
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=49995/" target="_blank">Fallen Lord\'s Handguards</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=54587/" target="_blank">Split Shape Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54586/" target="_blank">Foreshadow Steps</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': ['<a href="https://www.wowhead.com/wotlk/item=46051/" target="_blank">Meteorite Crystal</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=48724/" target="_blank">Talisman of Resurgence</a>'],
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>'],
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50616/" target="_blank">Bulwark of Smouldering Steel</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=40705/" target="_blank">Libram of Renewal</a>',
        },
        'RET AGILITY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51277/" target="_blank">T10 Head (Sanctified Lightsworn Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51279/" target="_blank">T10 Shoulders (Sanctified Lightsworn Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50653/" target="_blank">Shadowvault Slayer\'s Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51275/" target="_blank">T10 Chest (Sanctified Lightsworn Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50619/" target="_blank">Anub\'ar Stalker\'s Gloves</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51278/" target="_blank">T10 Legs (Sanctified Lightsworn Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=50706/" target="_blank">Tiny Abomination in a Jar</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50735/" target="_blank">Oathbinder, Charge of the Ranger-General</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=47661/" target="_blank">Libram of Valiance</a>', 
            '<a href="https://www.wowhead.com/wotlk/item=50455/" target="_blank">Libram of Three Truths</a>'],
        },
        'RET STRENGTH (AOE)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51277/" target="_blank">T10 Head (Sanctified Lightsworn Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51279/" target="_blank">T10 Shoulders (Sanctified Lightsworn Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50677/" target="_blank">Winding Sheet</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51275/" target="_blank">T10 Chest (Sanctified Lightsworn Battleplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50690/" target="_blank">Fleshrending Gauntlets</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51278/" target="_blank">T10 Legs (Sanctified Lightsworn Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=52572/" target="_blank">Ashen Band of Endless Might</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=47464/" target="_blank">Death\'s Choice</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=50706/" target="_blank">Tiny Abomination in a Jar</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>'],
            'Offhand/Shield': '-',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=47661/" target="_blank">Libram of Valiance</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50455/" target="_blank">Libram of Three Truths</a>'],
        },
        'PROT': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51269/" target="_blank">T10 Shoulders (Sanctified Lightsworn Shoulderguards)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51265/" target="_blank">T10 Chest (Sanctified Lightsworn Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51267/" target="_blank">T10 Hands (Sanctified Lightsworn Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51268/" target="_blank">T10 Legs (Sanctified Lightsworn Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54579/" target="_blank">Treads of Impending Resurrection</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': ['<a href="https://www.wowhead.com/wotlk/item=54591/" target="_blank">Petrified Twilight Scale</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=47451/" target="_blank">Juggernaut\'s Vitality</a>'],
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=50672/" target="_blank">Bloodvenom Blade</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50738/" target="_blank">Mithrios, Bronzebeard\'s Legacy</a>'],
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50729/" target="_blank">Icecrown Glacial Wall</a>',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=45145/" target="_blank">Libram of Sacred Shield</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=47661/" target="_blank">Libram of Valiance</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50461/" target="_blank">Libram of Eternal Tower</a>'],
        },
        'PROT (ARMOR)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51847/" target="_blank">Spaulders of the Blood Princes</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51265/" target="_blank">T10 Chest (Sanctified Lightsworn Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51267/" target="_blank">T10 Hands (Sanctified Lightsworn Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=49904/" target="_blank">Pillars of Might</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54579/" target="_blank">Treads of Impending Resurrection</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54591/" target="_blank">Petrified Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50738/" target="_blank">Mithrios, Bronzebeard\'s Legacy</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50729/" target="_blank">Icecrown Glacial Wall</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=45145/" target="_blank">Libram of Sacred Shield</a>',
        },
        'EXPERTISE SET': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51269/" target="_blank">T10 Shoulders (Sanctified Lightsworn Shoulderguards)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51265/" target="_blank">T10 Chest (Sanctified Lightsworn Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51267/" target="_blank">T10 Hands (Sanctified Lightsworn Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51268/" target="_blank">T10 Legs (Sanctified Lightsworn Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50625/" target="_blank">Grinning Skull Greatboots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54591/" target="_blank">Petrified Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50738/" target="_blank">Mithrios, Bronzebeard\'s Legacy</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50729/" target="_blank">Icecrown Glacial Wall</a>',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=45145/" target="_blank">Libram of Sacred Shield</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50461/" target="_blank">Libram of Eternal Tower</a>'],
        },
    },
    'Priest': {
        'SHADOW (BiS)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51255/" target="_blank">T10 Head (Sanctified Crimson Acolyte Cowl)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50658/" target="_blank">Amulet of Silent Eulogy</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51257/" target="_blank">T10 Shoulders (Sanctified Crimson Acolyte Mantle)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51259/" target="_blank">T10 Chest (Sanctified Crimson Acolyte Raiments)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50663/" target="_blank">Gunship Captain\'s Mittens</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51258/" target="_blank">T10 Legs (Sanctified Crimson Acolyte Pants)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'SHADOW (2nd BiS)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51255/" target="_blank">T10 Head (Sanctified Crimson Acolyte Cowl)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51257/" target="_blank">T10 Shoulders (Sanctified Crimson Acolyte Mantle)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51259/" target="_blank">T10 Chest (Sanctified Crimson Acolyte Raiments)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51256/" target="_blank">T10 Hands (Sanctified Crimson Acolyte Handwraps)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50614/" target="_blank">Loop of the Endless Labyrinth</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'DISCIPLINE': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51261/" target="_blank">T10 Head (Sanctified Crimson Acolyte Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51264/" target="_blank">T10 Shoulders (Sanctified Crimson Acolyte Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51259/" target="_blank">T10 Chest (Sanctified Crimson Acolyte Raiments) (Shadow Set)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51260/" target="_blank">T10 Hands (Sanctified Crimson Acolyte Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50702/" target="_blank">Lingering Illness</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51262/" target="_blank">T10 Legs (Sanctified Crimson Acolyte Leggings)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': ['<a href="https://www.wowhead.com/wotlk/item=50366/" target="_blank">Althor\'s Abacus</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=47271/" target="_blank">Solace of the Fallen</a>'],
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'DISCIPLINE - 2': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51261/" target="_blank">T10 Head (Sanctified Crimson Acolyte Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50700/" target="_blank">Holiday\'s Grace</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51264/" target="_blank">T10 Shoulders (Sanctified Crimson Acolyte Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51263/" target="_blank">T10 Chest (Sanctified Crimson Acolyte Robe)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51260/" target="_blank">T10 Hands (Sanctified Crimson Acolyte Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50702/" target="_blank">Lingering Illness</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51258/" target="_blank">T10 Legs (Sanctified Crimson Acolyte Pants) (Shadow)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50644/" target="_blank">Ring of Maddening Whispers</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=50366/" target="_blank">Althor\'s Abacus</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50631/" target="_blank">Nightmare Ender</a>',
        },
        'HOLY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51261/" target="_blank">T10 Head (Sanctified Crimson Acolyte Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50609/" target="_blank">Bone Sentinel\'s Amulet</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51264/" target="_blank">T10 Shoulders (Sanctified Crimson Acolyte Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50668/" target="_blank">Greatcloak of the Turned Champion</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50717/" target="_blank">Sanguine Silk Robes</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51260/" target="_blank">T10 Hands (Sanctified Crimson Acolyte Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51262/" target="_blank">T10 Legs (Sanctified Crimson Acolyte Leggings)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50636/" target="_blank">Memory of Malygos</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=50366/" target="_blank">Althor\'s Abacus</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=46017/" target="_blank">Val\'anyr, Hammer of Ancient Kings</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>'],
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50635/" target="_blank">Sundial of Eternal Dusk</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
    },
    'Rogue': {
        'COMBAT 2P': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51252/" target="_blank">T10 Head (Sanctified Shadowblade Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51254/" target="_blank">T10 Shoulders (Sanctified Shadowblade Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50656/" target="_blank">Ikfirus\'s Sack of Wonder</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>', '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards</a>'],
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50697/" target="_blank">Gangrenous Leggings</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50618/" target="_blank">Frostbrood Sapphire Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50654/" target="_blank">Scourgeborne Waraxe</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
        'COMBAT 4P': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51252/" target="_blank">T10 Head (Sanctified Shadowblade Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51254/" target="_blank">T10 Shoulders (Sanctified Shadowblade Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51250/" target="_blank">T10 Chest (Sanctified Shadowblade Breastplate)</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>', '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards</a>'],
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51253/" target="_blank">T10 Legs (Sanctified Shadowblade Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50654/" target="_blank">Scourgeborne Waraxe</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
        'ASSASSINATION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51252/" target="_blank">T10 Head (Sanctified Shadowblade Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51254/" target="_blank">T10 Shoulders (Sanctified Shadowblade Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50653/" target="_blank">Shadowvault Slayer\'s Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=50656/" target="_blank">Ikfirus\'s Sack of Wonder</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51251/" target="_blank">T10 Hands (Sanctified Shadowblade Gauntlets)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50707/" target="_blank">Astrylian\'s Sutured Cinch</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51253/" target="_blank">T10 Legs (Sanctified Shadowblade Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50607/" target="_blank">Frostbitten Fur Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50706/" target="_blank">Tiny Abomination in a Jar</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50736/" target="_blank">Heaven\'s Fall, Kryss of a Thousand Lies</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50621/" target="_blank">Lungbreaker</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
    },
    'Shaman': {
        'ELEMENTAL CRIT MULTI-TARGET': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51237/" target="_blank">T10 Head (Sanctified Frost Witch\'s Helm)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=50698/" target="_blank">Horrific Flesh Epaulets</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51239/" target="_blank">T10 Chest (Sanctified Frost Witch\'s Hauberk)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51238/" target="_blank">T10 Hands (Sanctified Frost Witch\'s Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=54587/" target="_blank">Split Shape Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51236/" target="_blank">T10 Legs (Sanctified Frost Witch\'s Kilt)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50614/" target="_blank">Loop of the Endless Labyrinth</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50616/" target="_blank">Bulwark of Smouldering Steel</a>',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=50458/" target="_blank">Bizuri\'s Totem of Shattered Ice</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=40267/" target="_blank">Totem of Hex</a>'],
        },
        'ELEMENTAL HASTE': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51237/" target="_blank">T10 Head (Sanctified Frost Witch\'s Helm)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51235/" target="_blank">T10 Shoulders (Sanctified Frost Witch\'s Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51239/" target="_blank">T10 Chest (Sanctified Frost Witch\'s Hauberk)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51238/" target="_blank">T10 Hands (Sanctified Frost Witch\'s Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=54587/" target="_blank">Split Shape Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50714/" target="_blank">Valanar\'s other Signet Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50616/" target="_blank">Bulwark of Smouldering Steel</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50458/" target="_blank">Bizuri\'s Totem of Shattered Ice</a>',
        },
        'RESTORATION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51247/" target="_blank">T10 Head (Sanctified Frost Witch\'s Headpiece)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50724/" target="_blank">Blood Queen\'s Crimson Choker</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51245/" target="_blank">T10 Shoulders (Sanctified Frost Witch\'s Spaulders)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51249/" target="_blank">T10 Chest (Sanctified Frost Witch\'s Tunic)</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>', '<a href="https://www.wowhead.com/wotlk/item=54584/" target="_blank">Phaseshifter\'s Bracers</a>'],
            'Hands': ['<a href="https://www.wowhead.com/wotlk/item=54560/" target="_blank">Changeling Gloves</a>', '<a href="https://www.wowhead.com/wotlk/item=50703/" target="_blank">Unclean Surgical Gloves</a>'],
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=54587/" target="_blank">Split Shape Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51246/" target="_blank">T10 Legs (Sanctified Frost Witch\'s Legguards)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=54585/" target="_blank">Ring of Phased Regeneration</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=54589/" target="_blank">Glowing Twilight Scale</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=47432/" target="_blank">Solace of the Fallen</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50734/" target="_blank">Royal Scepter of Terenas II</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50616/" target="_blank">Bulwark of Smouldering Steel</a>',
            'Relic/Ranged': ['<a href="https://www.wowhead.com/wotlk/item=47665/" target="_blank">Totem of Calming Tides</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=50458/" target="_blank">Bizuri\'s Totem of Shattered Ice</a>'],
        },
        'ENHANCEMENT SINGLE TARGET': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51242/" target="_blank">T10 Head (Sanctified Frost Witch\'s Faceguard)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50633/" target="_blank">Sindragosa\'s Cruel Claw</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51240/" target="_blank">T10 Shoulders (Sanctified Frost Witch\'s Shoulderguards)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50653/" target="_blank">Shadowvault Slayer\'s Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51244/" target="_blank">T10 Chest (Sanctified Frost Witch\'s Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=50655/" target="_blank">Scourge Hunter\'s Vambraces</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50619/" target="_blank">Anub\'ar Stalker\'s Gloves</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50688/" target="_blank">Nerub\'ar Stalker\'s Cord</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51241/" target="_blank">T10 Legs (Sanctified Frost Witch\'s War-Kilt)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54577/" target="_blank">Returning Footfalls</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50463/" target="_blank">Totem of the Avalanche</a>',
        },
        'ENHANCEMENT MULTI-TARGET': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51242/" target="_blank">T10 Head (Sanctified Frost Witch\'s Faceguard)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=51890/" target="_blank">Precious\'s Putrid Collar</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51240/" target="_blank">T10 Shoulders (Sanctified Frost Witch\'s Shoulderguards)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50653/" target="_blank">Shadowvault Slayer\'s Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51244/" target="_blank">T10 Chest (Sanctified Frost Witch\'s Chestguard)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50619/" target="_blank">Anub\'ar Stalker\'s Gloves</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50688/" target="_blank">Nerub\'ar Stalker\'s Cord</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51241/" target="_blank">T10 Legs (Sanctified Frost Witch\'s War-Kilt)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54577/" target="_blank">Returning Footfalls</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=54576/" target="_blank">Signet of Twilight</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50355/" target="_blank">Herkuml War Token</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50737/" target="_blank">Havoc\'s Call, Blade of Lordaeron Kings</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50458/" target="_blank">Bizuri\'s Totem of Shattered Ice</a>',
        },
    },
    'Warlock': {
        'DEMONOLOGY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51231/" target="_blank">T10 Head (Sanctified Dark Coven Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50658/" target="_blank">Amulet of Silent Eulogy</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51234/" target="_blank">T10 Shoulders (Sanctified Dark Coven Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51233/" target="_blank">T10 Chest (Sanctified Dark Coven Robe)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51230/" target="_blank">T10 Hands (Sanctified Dark Coven Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50714/" target="_blank">Valanar\'s other Signet Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'DESTRUCTION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51231/" target="_blank">T10 Head (Sanctified Dark Coven Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50658/" target="_blank">Amulet of Silent Eulogy</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51234/" target="_blank">T10 Shoulders (Sanctified Dark Coven Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51233/" target="_blank">T10 Chest (Sanctified Dark Coven Robe)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50663/" target="_blank">Gunship Captain\'s Mittens</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51232/" target="_blank">T10 Legs (Sanctified Dark Coven Leggings)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50714/" target="_blank">Valanar\'s other Signet Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50365/" target="_blank">Phylactery of the Nameless Lich</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
        'AFFLICTION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51231/" target="_blank">T10 Head (Sanctified Dark Coven Hood)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50658/" target="_blank">Amulet of Silent Eulogy</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51234/" target="_blank">T10 Shoulders (Sanctified Dark Coven Shoulderpads)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=54583/" target="_blank">Cloak of Burning Dusk</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51233/" target="_blank">T10 Chest (Sanctified Dark Coven Robe)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=54582/" target="_blank">Bracers of Fiery Night</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51230/" target="_blank">T10 Hands (Sanctified Dark Coven Gloves)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50613/" target="_blank">Crushing Coldwraith Belt</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50694/" target="_blank">Plaguebringer\'s Stained Pants</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=50699/" target="_blank">Plague Scientist\'s Boots</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50398/" target="_blank">Ashen Band of Endless Destruction</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50664/" target="_blank">Ring of Rapid Ascent</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50348/" target="_blank">Dislodged Foreign Object</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54588/" target="_blank">Charred Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50732/" target="_blank">Bloodsurge, Kel\'Thuzad\'s Blade of Agony</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50719/" target="_blank">Shadow Silk Spindle</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50684/" target="_blank">Corpse Impaling Spike</a>',
        },
    },
    'Warrior': {
        'FURY': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51227/" target="_blank">T10 Head (Sanctified Ymirjar Lord\'s Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51229/" target="_blank">T10 Shoulders (Sanctified Ymirjar Lord\'s Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51225/" target="_blank">T10 Chest (Sanctified Ymirjar Lord\'s Battleplate)</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands</a>', '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards</a>'],
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=50675/" target="_blank">Aldriana\'s Gloves of Secrecy</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=51228/" target="_blank">T10 Legs (Sanctified Ymirjar Lord\'s Legplates)</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50618/" target="_blank">Frostbrood Sapphire Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Shadowmourne</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
        'Fury (No SM)': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=51227/" target="_blank">T10 Head (Sanctified Ymirjar Lord\'s Helmet)</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=54581/" target="_blank">Penumbra Pendant</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51229/" target="_blank">T10 Shoulders (Sanctified Ymirjar Lord\'s Shoulderplates)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=47546/" target="_blank">Sylvana\'s Cunning</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51225/" target="_blank">T10 Chest (Sanctified Ymirjar Lord\'s Battleplate)</a>',
            'Wrist': ['<a href="https://www.wowhead.com/wotlk/item=54580/" target="_blank">Umbrage Armbands', '<a href="https://www.wowhead.com/wotlk/item=50670/" target="_blank">Toskk\'s Maximized Wristguards'],
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51226/" target="_blank">T10 Hands (Sanctified Ymirjar Lord\'s Gauntlets)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50620/" target="_blank">Coldwraith Links</a>',
            'Legs': '<a href="https://www.wowhead.com/wotlk/item=50645/" target="_blank">Leggings of Northern Lights</a>',
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54578/" target="_blank">Apocalypse\'s Advance	</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50402/" target="_blank">Ashen Band of Endless Vengeance</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=50618/" target="_blank">Frostbrood Sapphire Ring</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50363/" target="_blank">Deathbringer\'s Will</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54590/" target="_blank">Sharpened Twilight Scale</a>',
            'Weapon': '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>',
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50730/" target="_blank">Glorenzelg, High-Blade of the Silver Hand</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=50733/" target="_blank">Fal\'inrush, Defender of Quel\'thalas</a>',
        },
        'PROTECTION': {
            'Head': '<a href="https://www.wowhead.com/wotlk/item=50640/" target="_blank">Broken Ram Skull Helm</a>',
            'Neck': '<a href="https://www.wowhead.com/wotlk/item=50682/" target="_blank">Bile-Encrusted Medallion</a>',
            'Shoulders': '<a href="https://www.wowhead.com/wotlk/item=51224/" target="_blank">T10 Shoulders (Sanctified Ymirjar Lord\'s Pauldrons)</a>',
            'Back': '<a href="https://www.wowhead.com/wotlk/item=50466/" target="_blank">Sentinel\'s Winter Cloak</a>',
            'Chest': '<a href="https://www.wowhead.com/wotlk/item=51220/" target="_blank">T10 Chest (Sanctified Ymirjar Lord\'s Breastplate)</a>',
            'Wrist': '<a href="https://www.wowhead.com/wotlk/item=51901/" target="_blank">Gargoyle Spit Bracers</a>',
            'Hands': '<a href="https://www.wowhead.com/wotlk/item=51222/" target="_blank">T10 Hands (Sanctified Ymirjar Lord\'s Handguards)</a>',
            'Waist': '<a href="https://www.wowhead.com/wotlk/item=50991/" target="_blank">Verdigris Chain Belt</a>',
            'Legs': ['<a href="https://www.wowhead.com/wotlk/item=51223/" target="_blank">T10 Legs (Sanctified Ymirjar Lord\'s Legguards)</a>', 
                '<a href="https://www.wowhead.com/wotlk/item=49904/" target="_blank">Pillars of Might</a>'],
            'Feet': '<a href="https://www.wowhead.com/wotlk/item=54579/" target="_blank">Treads of Impending Resurrection</a>',
            'Ring 1': '<a href="https://www.wowhead.com/wotlk/item=50622/" target="_blank">Devium\'s Eternally Cold Ring</a>',
            'Ring 2': '<a href="https://www.wowhead.com/wotlk/item=49489/" target="_blank">Signified ring of Binding</a>',
            'Trinket 1': '<a href="https://www.wowhead.com/wotlk/item=50364/" target="_blank">Sindragosa\'s Flawless Fang</a>',
            'Trinket 2': '<a href="https://www.wowhead.com/wotlk/item=54591/" target="_blank">Petrified Twilight Scale</a>',
            'Weapon': ['<a href="https://www.wowhead.com/wotlk/item=49623/" target="_blank">Bloodvenom Blade</a>', '<a href="https://www.wowhead.com/wotlk/item=50738/" target="_blank">Mithrios, Bronzebeard\'s Legacy</a>'],
            'Offhand/Shield': '<a href="https://www.wowhead.com/wotlk/item=50729/" target="_blank">Icecrown Glacial Wall</a>',
            'Relic/Ranged': '<a href="https://www.wowhead.com/wotlk/item=51834/" target="_blank">Dreamhunter\'s Carbine</a>',
        },
    },
}
